name: Tool Cache
description: Implementation of Tool Cache in composite GitHub Actions
branding:
  icon: plus
  color: purple
inputs:
  folder_name:
    description: Folder name of the software inside runner temp
    required: true
  cache-hit:
    description: Boolean value if cache was found
    required: false
    default: false
    
runs:
  using: composite
  steps:
    - name: Install software to tool cache (Unix-like)
      if: (runner.os == 'Linux' || runner.os == 'macOS') && inputs.cache-hit != 'true'
      shell: bash
      env:
        folder_name: ${{ inputs.folder_name }}
      run: $GITHUB_ACTION_PATH/scripts/Unix-like.sh
      
    - name: Add software tool cache folder to path (Unix-like)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        echo ::group::Adding tool cache to path
        echo "$RUNNER_TOOL_CACHE/${{ inputs.folder_name }}" >> $GITHUB_PATH
        echo ::endgroup::
        
    - name: Install software to tool cache (Windows)
      if: runner.os == 'Windows' && inputs.cache-hit != 'true'
      shell: pwsh
      env:
        folder_name: ${{ inputs.folder_name }}
      run: '& $env:GITHUB_ACTION_PATH\scripts\Windows.ps1'
      
    - name: Add software tool cache folder to path (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Write-Host "::group::Adding tool cache to path"
        Add-Content $env:GITHUB_PATH "$env:RUNNER_TOOL_CACHE\${{ inputs.folder_name }}"
        Write-Host "::endgroup::"